# Generated by Django 4.2.3 on 2024-02-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.user"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(to="news.category"),
        ),
    ]
